[tool.poetry]
name = "gppop-neo"
version = "0.1.0"
description = ""
authors = ["Cory Chu <cory@gwlab.page>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "1.25.2"
pymc = "4.4.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
ipywidgets = "^8.1.5"

[tool.poetry.group.jax.dependencies]
numpyro = "^0.10"
jax = "0.4.6"
jaxlib = "0.4.6"
scipy = "<=1.12.0,>= 1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
